subprojects { project ->
    if (project.name == "file_picker") {
        project.apply plugin: 'org.jetbrains.kotlin.android'
        project.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
            kotlinOptions {
                jvmTarget = "17"
            }
        }
    }
    afterEvaluate {
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
                compileSdkVersion 36
            }
        }
    }
}
